spring.application.name=torneo-calcio
spring.datasource.url=jdbc:postgresql://localhost:5432/torneo_calcio
spring.datasource.username=matteo
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#===== spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.content-type=text/html
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
#==================================
# = Messages configuration
#==================================
spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8
#==================================
# = Logging configuration
#==================================logging.level.root=INFO
##logging.level.it.uniroma3.siw.movie.controller.MovieController==DEBUG

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/




