spring.application.name=torneo-calcio

# Database Azure
spring.datasource.url=jdbc:postgresql://torneo-calcio-db.postgres.database.azure.com:5432/torneo_calcio?sslmode=require
spring.datasource.username=torneoadmin
spring.datasource.password=TorneoCalcio2026!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=true
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.content-type=text/html

# SQL init
spring.sql.init.mode=never

# Messages
spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8

# Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.web.resources.static-locations=classpath:/static/,file:/home/uploads/

# Logging
logging.level.root=WARN